# Hyperparameters
train_epoch: 100
early_stop_epoch: 5
learning_rate: 1

# Model dump path
save_path: 'out/base_model'
restore_path: 'out/base_model'
# Trace data dump path
trace_path: 'out/base_data'

# device
device: cuda

# Model
model_name: 'SimpleReverberator'
max_seq_len: 20
hidden_size: 40 
num_layers: 1 # number of LSTM layers

# DSP params

# multi-scale fft
fft_scales: 
    - 128 # base
    - 1 # exp
overlap: 0.75

# Imported data
train_dataset:
    name: 'VAST'
    datadir: './dataset/VAST/test'
    anechoic: './dataset/VAST/anechoic.mat'
    num_workers: 1
    n_mfcc: 33
    transforms: None
    batch_size: 20

val_dataset: 
    name: 'VAST'
    datadir: './dataset/VAST/val'
    anechoic: './dataset/VAST/anechoic.mat'
    num_workers: 1
    n_mfcc: 33
    transforms: None
    batch_size: 20

test_dataset: 
    name: 'VAST'
    datadir: './dataset/VAST/test'
    anechoic: './dataset/VAST/anechoic.mat'
    num_workers: 1
    n_mfcc: 33
    transforms: None
    batch_size: 20
